### ISSUE TITLE
squared_DTW out of bounds error

### ISSUE THREAD

**Issue by cmuell89** [fpetitjean/DBA#5]
When the number of channels is greater than the max length of a series, the squared_DTW failes in the following loop:
`for i in range(1, s_len):
        cost_mat[i, 0] = cost_mat[i-1, 0]+delta_mat[i, 0]
`

Why should the cost matrix and delta_mat depend on the number of features in my feature vector?

**Comment by fpetitjean** [comment]
Hi, 
Stupid bug - fixed now (the question is how did this ever worked?!). 
Python is pretty slow though, if you have issues with performance, I could make a Cython one. 
Cheers, 
François
